import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Tyler',
      email: 'admin@cs.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Kayla',
      email: 'user@cs.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'High Air',
      slug: 'high-air',
      catagory: 'Mens Shoe',
      image: '/images/af1highstyle.jpg',
      price: 160,
      brand: 'RoyalFree',
      countInStock: 25,
      description: 'Leather High Top Basketball Inspired Shoe',
    },
    {
      name: 'Low Air',
      slug: 'low-air',
      catagory: 'Mens Shoe',
      image: '/images/af1style.jpg',
      price: 120,
      brand: 'RoyalFree',
      countInStock: 20,
      description: 'Leather Low Top Basketball Inspired Shoe',
    },
    {
      name: 'Low Sport',
      slug: 'low-sport',
      catagory: 'Mens Shoe',
      image: '/images/lowsneaker.jpg',
      price: 100,
      brand: 'RoyalFree',
      countInStock: 27,
      description: 'Low Top Athletic Everyday Shoe',
    },
    {
      name: 'Verse',
      slug: 'verse',
      catagory: 'Unisex Shoe',
      image: '/images/convstyle.jpg',
      price: 90,
      brand: 'RoyalFree',
      countInStock: 30,
      description: 'Canvas Everyday Shoe',
    },
    {
      name: 'Trainer',
      slug: 'trainer',
      catagory: 'Mens Shoe',
      image: '/images/trainer.jpg',
      price: 150,
      brand: 'RoyalFree',
      countInStock: 23,
      description: 'Mid Top Supportive Training Shoe',
    },
    {
      name: 'Skate Low',
      slug: 'skate-low',
      catagory: 'Mens Shoe',
      image: '/images/skateshoe.jpg',
      price: 110,
      brand: 'RoyalFree',
      countInStock: 25,
      description: 'Sleek Skateboarding Shoe',
    },
    {
      name: 'SuperComf',
      slug: 'supercomf',
      catagory: 'Womens Shoe',
      image: '/images/sportsshoe.jpg',
      price: 150,
      brand: 'RoyalFree',
      countInStock: 25,
      description: 'Super Cushioned Sporty Shoe',
    },
    {
      name: 'Retro Sport',
      slug: 'retro-sport',
      catagory: 'Womens Shoe',
      image: '/images/am90style.jpg',
      price: 170,
      brand: 'RoyalFree',
      countInStock: 20,
      description: 'Retro Shoe Bringing Back The Styles From The 90s',
    },
    {
      name: 'SuperSport',
      slug: 'supersport',
      catagory: 'Womens Shoe',
      image: '/images/wsports.jpg',
      price: 140,
      brand: 'RoyalFree',
      countInStock: 27,
      description: 'Athletic Everyday Shoe With New School Twists',
    },
    {
      name: 'UniStreet',
      slug: 'unistreet',
      catagory: 'Unisex Shoe',
      image: '/images/unisexsport.jpg',
      price: 130,
      brand: 'RoyalFree',
      countInStock: 23,
      description: 'Shoe With No Restrictions',
    },
    {
      name: 'W Skate Low',
      slug: 'w-skate-low',
      catagory: 'Womens Shoe',
      image: '/images/yelloepurplow.jpg',
      price: 110,
      brand: 'RoyalFree',
      countInStock: 25,
      description: 'Balanced Skateboarding Shoe',
    },
  ],
};

export default data;
