const mendata = {
  products: [
    {
      name: 'High Air',
      slug: 'high-air',
      catagory: 'Mens Shoe',
      image: '/images/af1highstyle.jpg',
      price: 160,
      brand: 'RoyalFree',
      countInStock: 25,
      description: 'Leather High Top Basketball Inspired Shoe',
    },
    {
      name: 'Low Air',
      slug: 'low-air',
      catagory: 'Mens Shoe',
      image: '/images/af1style.jpg',
      price: 120,
      brand: 'RoyalFree',
      countInStock: 20,
      description: 'Leather Low Top Basketball Inspired Shoe',
    },
    {
      name: 'Low Sport',
      slug: 'low-sport',
      catagory: 'Mens Shoe',
      image: '/images/lowsneaker.jpg',
      price: 100,
      brand: 'RoyalFree',
      countInStock: 27,
      description: 'Low Top Athletic Everyday Shoe',
    },
    {
      name: 'Verse',
      slug: 'verse',
      catagory: 'Mens Shoe',
      image: '/images/convstyle.jpg',
      price: 90,
      brand: 'RoyalFree',
      countInStock: 30,
      description: 'Canvas Everyday Shoe',
    },
    {
      name: 'Trainer',
      slug: 'trainer',
      catagory: 'Mens Shoe',
      image: '/images/trainer.jpg',
      price: 150,
      brand: 'RoyalFree',
      countInStock: 23,
      description: 'Mid Top Supportive Training Shoe',
    },
    {
      name: 'Skate Low',
      slug: 'skate-low',
      catagory: 'Mens Shoe',
      image: '/images/skateshoe.jpg',
      price: 110,
      brand: 'RoyalFree',
      countInStock: 25,
      description: 'Sleek Skateboarding Shoe',
    },
  ],
};

export default mendata;
