const womendata = {
  products: [
    {
      name: 'SuperComf',
      slug: 'supercomf',
      catagory: 'Womens Shoe',
      image: '/images/sportsshoe.jpg',
      price: 150,
      brand: 'RoyalFree',
      countInStock: 25,
      description: 'Super Cushioned Sporty Shoe',
    },
    {
      name: 'Retro Sport',
      slug: 'retro-sport',
      catagory: 'Womens Shoe',
      image: '/images/am90style.jpg',
      price: 170,
      brand: 'RoyalFree',
      countInStock: 20,
      description: 'Retro Shoe Bringing Back The Styles From The 90s',
    },
    {
      name: 'SuperSport',
      slug: 'supersport',
      catagory: 'Womens Shoe',
      image: '/images/wsports.jpg',
      price: 140,
      brand: 'RoyalFree',
      countInStock: 27,
      description: 'Athletic Everyday Shoe With New School Twists',
    },
    {
      name: 'Verse',
      slug: 'verse',
      catagory: 'Womens Shoe',
      image: '/images/convstyle.jpg',
      price: 90,
      brand: 'RoyalFree',
      countInStock: 30,
      description: 'Canvas Everyday Shoe',
    },
    {
      name: 'UniStreet',
      slug: 'unistreet',
      catagory: 'Unisex Shoe',
      image: '/images/unisexsport.jpg',
      price: 130,
      brand: 'RoyalFree',
      countInStock: 23,
      description: 'Shoe With No Restrictions',
    },
    {
      name: 'W Skate Low',
      slug: 'w-skate-low',
      catagory: 'Womens Shoe',
      image: '/images/yelloepurplow.jpg',
      price: 110,
      brand: 'RoyalFree',
      countInStock: 25,
      description: 'Balanced Skateboarding Shoe',
    },
  ],
};

export default womendata;
